alarm_panel_eventlog:
  fields:
    code:
      example: "1234"
      default: "0000"
      selector:
        text:
    panel:
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 9

alarm_panel_command:
  fields:
    command:
      required: true
      example: 'disarm'
      selector:
        select:
          options:
            - "disarm"
            - "arm_home"
            - "arm_home_instant"
            - "arm_away"
            - "arm_away_instant"
    code:
      example: "1234"
      default: "0000"
      selector:
        text:
    panel:
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 9

alarm_panel_reconnect:
  fields:
    panel:
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 9

alarm_sensor_bypass:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: visonic
          domain: binary_sensor
    bypass:
      required: true
      example: "Off"
      selector:
        select:
          options:
            - "On"
            - "Off"
    code:
      required: true
      example: "1234"
      default: "0000"
      selector:
        text:
    panel:
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 9
  